WIP #416: simplify tests.

diff --git a/workshops/oracleteq-kafka/springboot-kafka/kafka-ms-launch-consumer b/workshops/oracleteq-kafka/springboot-kafka/kafka-ms-launch-consumer
--- a/workshops/oracleteq-kafka/springboot-kafka/kafka-ms-launch-consumer
+++ b/workshops/oracleteq-kafka/springboot-kafka/kafka-ms-launch-consumer
@@ -5,24 +5,23 @@
 # Fail on error
 set -e
 
-## Launch Kafka producer microservice.
-echo "Launching Kafka producer microservice!"
+## Launch Kafka consumer microservice.
+echo "Launching Kafka consumer microservice!"
 
-container_name="kafka-producer"
+container_name="kafka-consumer"
 docker run --detach \
            --name=${container_name} \
            --network $(state_get LAB_KAFKA_NETWORK) \
-           -p 8080:8080 \
-           oracle-developers-kafka-producer:0.0.1-SNAPSHOT
+           oracle-developers-kafka-consumer:0.0.1-SNAPSHOT
 
-if ! state_done KAFKA_MS_PRODUCER_LAUNCHED; then
-  echo "$(date): Waiting for producer running!"
+if ! state_done KAFKA_MS_CONSUMER_LAUNCHED; then
+  echo "$(date): Waiting for consumer running!"
   sleep 3
   echo
 fi
 
 if [ "$( docker container inspect -f '{{.State.Status}}' ${container_name} )" == "running" ]; then
-  echo "Kafka producer microservice is running!";
+  echo "Kafka consumer microservice is running!";
 else
-  echo "Kafka producer microservice launching failed!";
+  echo "Kafka consumer microservice launching failed!";
 fi
